
**Section 1: Welcome**
```
# Data Loading Beginner Guide

Welcome to Machine Learning Practice Guide.

In this notebook you will learn:

✅ What is a dataset

✅ What is a CSV file

✅ How to load data using Pandas

✅ How to inspect a dataset

✅ Understanding rows and columns

✅ Understanding data types

No Machine Learning knowledge required.
```

**Section 2: What is a Dataset?**

```
# What is a Dataset?

A dataset is a collection of information.

Example:

| Name   | Age    | City   |
|--------|--------|--------|
| Ram    | 15     | Chennai|
| John   | 16     | Mumbai |
| Ravi   | 15     | Delhi  |

Each row represents a record.

Each column represents a feature.
```

**Section 3: Import Pandas**

In [2]:
import pandas as pd



```
# What happened?

Pandas is a Python library used for working with data.

Think of Pandas as Excel inside Python.
```

**Section 4: Load Dataset**

`Mount your Google Drive to load your Dataset`

In [14]:
# If you are using a standard personal Google Drive account:
car_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Datasets/auto_mpg_binarised.csv')

## What happened?

```
pd.read_csv('your_file_name')

reads the CSV file and converts it into a DataFrame.

A DataFrame is a table-like structure.

Think of it as an Excel sheet stored in memory.
```

**Section 5: View First 5 Rows**

In [13]:
car_data.head()

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name,mpg_high
0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu,0
1,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320,0
2,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite,0
3,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst,0
4,8,302.0,140.0,3449.0,10.5,70,1,ford torino,0


## Why use head()?
```
Datasets may contain hundreds or thousands of rows.

head() shows only the first 5 rows.

This helps us quickly inspect the data.
```

**Section 6: Dataset Shape**

In [ ]:
car_data.shape

(398, 9)

## Understanding Shape
```
Output Example:

(398, 8)

Meaning:

398 Rows

8 Columns

Rows = Records

Columns = Features
```

**Section 7: Column Names**

In [ ]:
car_data.columns

Index(['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration',
       'model_year', 'origin', 'car_name', 'mpg_high'],
      dtype='object')

## Why check column names?

```
Column names tell us what information is available.

Example:

cylinders
horsepower
weight
origin

These are called features.
```

**Section 8: Dataset Information**

In [ ]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cylinders     398 non-null    int64
 1   displacement  398 non-null    float64
 2   horsepower    398 non-null    float64
 3   weight        398 non-null    float64
 4   acceleration  398 non-null    float64
 5   model_year    398 non-null    int64
 6   origin        398 non-null    int64
 7   car_name      398 non-null    object
 8   mpg_high      398 non-null    int64
dtypes: float64(4), int64(4), object(1)
memory usage: 28.1+ KB


## Understanding info()
```
info() shows:

1. Column Names

2. Number of Non-Null Values

3. Data Types

4. Memory Usage

This is usually the first thing a Data Analyst checks.
```

**Section 9: Data Types**

In [ ]:
car_data.dtypes

cylinders         int64
displacement    float64
horsepower      float64
weight          float64
acceleration    float64
model_year        int64
origin            int64
car_name         object
mpg_high          int64
dtype: object


## Common Data Types
```
int64
Whole numbers

Example:
1, 2, 3

float64
Decimal numbers

Example:
12.5, 18.7

object
Text values

Example:
India, USA
```

**Section 10: Statistical Summary**

In [ ]:
car_data.describe()

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,mpg_high
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,1.572864,0.479899
std,1.701004,104.269838,38.199187,846.841774,2.757689,3.697627,0.802055,0.500225
min,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000,0.000000
25%,4.000000,104.250000,76.000000,2223.750000,13.825000,73.000000,1.000000,0.000000
50%,4.000000,148.500000,95.000000,2803.500000,15.500000,76.000000,1.000000,0.000000
75%,8.000000,262.000000,125.000000,3608.000000,17.175000,79.000000,2.000000,1.000000
max,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000,1.000000

## What is describe()?

```
describe() provides:

  Count

  Mean

  Standard Deviation

  Minimum Value

  Maximum Value

  Quartiles

Useful for understanding numerical data.
```

**Section 11: Count Missing Values**

In [ ]:
car_data.isnull().sum()

cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
car_name        0
mpg_high        0
dtype: int64

## Why check missing values?

```
Machine Learning algorithms do not like missing values.

Before training a model we must identify missing data.
```

**Section 12: Count Unique Values**

In [ ]:
for column in car_data.columns:
  unique_count = car_data[column].nunique()
  print(f"Unique values in {column}: {unique_count}")

Unique values in cylinders: 5
Unique values in displacement: 82
Unique values in horsepower: 94
Unique values in weight: 351
Unique values in acceleration: 95
Unique values in model_year: 13
Unique values in origin: 3
Unique values in car_name: 305
Unique values in mpg_high: 2

## Why check unique values?

```
It helps us understand the variety of data.

Example:

  Origin
    USA
    Europe
    Japan
Unique Values = 3
```

**Section 13: Practice Exercises**

## Practice Exercises

```
Exercise 1

Display the last 10 rows.

Hint:
tail()

--------------------------------

Exercise 2

Print total number of rows.

--------------------------------

Exercise 3

Print total number of columns.

--------------------------------

Exercise 4

Display only column names.

--------------------------------

Exercise 5

Find which column has the highest number of unique values.
```

**Section 14: Interview Questions**



```
# Interview Questions

1. What is a dataset?

2. What is a DataFrame?

3. Difference between rows and columns?

4. What does head() do?

5. What does shape return?

6. What does info() return?

7. What is a data type?

8. Why do we check missing values?

9. What is the purpose of describe()?

10. What are features in Machine Learning?
```

**Section 15: Learning Summary**



```
# What You Learned

✅ Dataset

✅ CSV Files

✅ Pandas

✅ DataFrame

✅ Rows and Columns

✅ Shape

✅ Columns

✅ Data Types

✅ Missing Values

✅ Statistical Summary

You are now ready for:

02_Missing_Value_Handling_Beginner_Guide.ipynb
```

**Answer for practical questions**

In [ ]:
car_data.tail()

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name,mpg_high
393,4,140.0,86.0,2790.0,15.6,82,1,ford mustang gl,1
394,4,97.0,52.0,2130.0,24.6,82,2,vw pickup,1
395,4,135.0,84.0,2295.0,11.6,82,1,dodge rampage,1
396,4,120.0,79.0,2625.0,18.6,82,1,ford ranger,1
397,4,119.0,82.0,2720.0,19.4,82,1,chevy s-10,1

In [ ]:
car_data.shape[0] #total number of rows
car_data.shape[1] #total number of columns

9

In [ ]:
car_data.columns.tolist() #display only column names

['cylinders',
 'displacement',
 'horsepower',
 'weight',
 'acceleration',
 'model_year',
 'origin',
 'car_name',
 'mpg_high']

In [ ]:
car_data.nunique().idxmax() #column has maximum number of unique values

'weight'

In [ ]:
highest_unique_count = 0
column_name = ""

for col in car_data.columns:

    unique_count = car_data[col].nunique()

    if unique_count > highest_unique_count:
        highest_unique_count = unique_count
        column_name = col

print("Column:", column_name)
print("Unique Values:", highest_unique_count)

Column: weight
Unique Values: 351